version: "3"

services:
  server:
    image: 12laboursapi:latest
    ports:
      - "8000:8000"
    environment:
      QUERY_API_URL: ${QUERY_API_URL}
      GEN3_ENDPOINT_URL: ${GEN3_ENDPOINT_URL}
      GEN3_API_KEY: ${GEN3_API_KEY}
      GEN3_KEY_ID: ${GEN3_KEY_ID}
      IRODS_ENDPOINT_URL: ${IRODS_ENDPOINT_URL}
      IRODS_HOST: ${IRODS_HOST}
      IRODS_PORT: ${IRODS_PORT}
      IRODS_USER: ${IRODS_USER}
      IRODS_PASSWORD: ${IRODS_PASSWORD}
      IRODS_ZONE: ${IRODS_ZONE}
